SERVER_IP = '192.168.1.83'
SERVER_PORT = 4548 

RETRY_SERVER_CONEXION_SECS = 20

ID_CLIENT = 1
ID_CAMERA = 1
CAMERA_NAME = 'Habitacion'

'''
320x240
640x480
1920x1080
'''

WIDTH_FRAME = 640
HEIGHT_FRAME = 480

FRAME_RATE = 30
ISO = 300

FRAME_FORMAT = 'png'

BACKFILL_CHARACTER_STRINGS = "*"
MAX_CAM_NAME_BYTES = 20

#TO SERVER SIGNALS
#Todas las señales de envío hacia el servidor han de ser int negativos
CONFIRM_STOP_STREAMING_TO_SERVER_SIGNAL = -2341
CONFIRM_SHUTDOWN_CAMERA_TO_SERVER_SIGNAL = -6732

#FROM SERVER SIGNALS
START_STREAMING_FROM_SERVER_SIGNAL = 54
STOP_STREAMING_FROM_SERVER_SIGNAL = 34
SHUTDOWN_CAMERA_FROM_SERVER_SIGNAL = 78
